In [ ]:
import pandas as pd

df = pd.read_csv("salaries_by_college_major.csv")

#df.head() --> Peek the first 5 rows
#df.shape --> (n rows, n columns)
#df.columns  --> list of column names
#df.isna() --> detects missing values and returns a boolean dataframe
#df.tail() --> Peek the last 5 rows
clean_df = df.dropna() # drops all rows with missing values
#clean_df.tail()
#clean_df["Starting Median Salary"].max()
#clean_df["Starting Median Salary"].idxmax()
#clean_df["Starting Median Salary"].loc[43]
#clean_df["Undergraduate Major"].loc[43]
#clean_df.loc[43]

np.float64(107000.0)

#### What college major has the highest mid-career salary? How much do graduates with this major earn? (Mid-career is defined as having 10+ years of experience).

In [61]:
print(clean_df["Undergraduate Major"].loc[clean_df['Mid-Career Median Salary'].idxmax()])
print(clean_df['Mid-Career Median Salary'].max())

Chemical Engineering
107000.0

#### Which college major has the lowest starting salary and how much do graduates earn after university?

In [62]:
print(clean_df["Undergraduate Major"].loc[clean_df["Starting Median Salary"].idxmin()])
print(clean_df["Starting Median Salary"].min())

Spanish
34000.0

#### Which college major has the lowest mid-career salary and how much can people expect to earn with this degree?

In [63]:
print(clean_df["Undergraduate Major"].loc[clean_df["Mid-Career Median Salary"].idxmin()])
print(clean_df["Mid-Career Median Salary"].min())

Education
52000.0

### Lowest Risk Majors
#### A low-risk major is a degree where there is a small difference between the lowest and highest salaries. In other words, if the difference between the 10th percentile and the 90th percentile earnings of your major is small,

In [64]:
spread_col = clean_df["Mid-Career 90th Percentile Salary"] - clean_df["Mid-Career 10th Percentile Salary"]
clean_df.insert(1, "Spread", spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"109,800.00","46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"96,700.00","57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"113,700.00","42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"104,200.00","36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"85,400.00","41,600.00","76,800.00","50,600.00","136,000.00",Business

#### Using the .sort_values() method, can you find the degrees with the highest potential?

In [69]:
highest_potential = clean_df.sort_values("Mid-Career 90th Percentile Salary", ascending=False)
print(highest_potential[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].head())

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                         210,000.00
22               Finance                         195,000.00
8   Chemical Engineering                         194,000.00
37                  Math                         183,000.00
44               Physics                         178,000.00

#### Majors with the Greatest Spread in Salaries

In [70]:
spread_col = clean_df["Mid-Career 90th Percentile Salary"] - clean_df["Mid-Career 10th Percentile Salary"]
clean_df.insert(1, "Spread", spread_col)
highest_spread = clean_df.sort_values("Spread", ascending=False)
print(highest_spread[["Undergraduate Major", "Spread"]].head())

   Undergraduate Major     Spread
17           Economics 159,400.00
22             Finance 147,800.00
37                Math 137,800.00
36           Marketing 132,900.00
42          Philosophy 132,500.00

#### Highest spread Median

In [71]:
spread_col = clean_df.sort_values("Mid-Career Median Salary", ascending=False)
print(spread_col[["Undergraduate Major", "Mid-Career Median Salary"]].head())

       Undergraduate Major  Mid-Career Median Salary
8     Chemical Engineering                107,000.00
12    Computer Engineering                105,000.00
19  Electrical Engineering                103,000.00
1    Aerospace Engineering                101,000.00
17               Economics                 98,600.00

### Group count

In [72]:
#print(clean_df.groupby('Group').count())
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"